### PR TITLE
Fix the statistics collection and reporting in perf_client/triton server

### LINKED ISSUE #2137: The overhead cost so much time
I used perf_client to test perfomance, but the overthead cost extremely too much time with perf_client running on both server host and other machine. the details is followed below.

using triton-inference-server v2.3.0dev
### model config
name: "test_model"
platform: "tensorrt_plan"
max_batch_size: 8
dynamic_batching {
  preferred_batch_size: [2, 4, 8]
  max_queue_delay_microseconds: 0
}
input [
  {
    name: "data"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 384, 640, 3 ]
  }
]
output[
  {
    name:"prob"
    data_type:TYPE_FP32
    dims:[6001,1,1]
  }
]

instance_group [
  {
    count:8
    gpus:1
    kind: KIND_GPU
  }
]

### server start config
--allow-http=true  --allow-grpc=true --grpc-infer-allocation-pool-size=100  --strict-readiness=false --log-verbose=3 --log-info=true --log-warning=true

### perf_client config
./perf_client  -m test_model --concurrency-range 1 -u 192.168.54.181:8000

### performance result from client side
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client:
    Request count: 41
    Throughput: 8.2 infer/sec
    Avg latency: 120590 usec (standard deviation 20704 usec)
    p50 latency: 115669 usec
    p90 latency: 139971 usec
    p95 latency: 143088 usec
    p99 latency: 225839 usec
    Avg HTTP time: 118252 usec (send/recv 1311 usec + response wait 116941 usec)
  Server:
    Inference count: 51
    Execution count: 51
    Successful request count: 51
    Avg request latency: 517080879457 usec (overhead 517080863048 usec + queue 94 usec + compute input 4040 usec + compute infer 12199 usec + compute output 76 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 8.2 infer/sec, latency 120590 usec

### performance result from server side
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client:
    Request count: 392
    Throughput: 78.4 infer/sec
    Avg latency: 12744 usec (standard deviation 182 usec)
    p50 latency: 12711 usec
    p90 latency: 12813 usec
    p95 latency: 12940 usec
    p99 latency: 13082 usec
    Avg HTTP time: 12744 usec (send/recv 1949 usec + response wait 10795 usec)
  Server:
    Inference count: 470
    Execution count: 470
    Successful request count: 470
    Avg request latency: 519608163228 usec (overhead 519608155497 usec + queue 111 usec + compute input 3902 usec + compute infer 3645 usec + compute output 73 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 78.4 infer/sec, latency 12744 usec

As the overhead time mentioned by @dselivanov in #1989 , the input dims were dims: [3, 2048, 2048] and the overhead time was only 67.62230263157895us, but mine was very much longer.

I also used the python to test. 
### python  infer time
preprocess time: 0.0029985904693603516
infer time: 0.9250223636627197
preprocess time: 0.0029108524322509766
infer time: 1.1599602699279785
preprocess time: 0.0030019283294677734
infer time: 0.957021951675415
preprocess time: 0.0029993057250976562
infer time: 1.0499982833862305
preprocess time: 0.003998994827270508
infer time: 0.618964433670044

Hope someone to help, Thanks very much~

### PR DESCRIPTION
**Pull request by tanmayv25**
The cases fixed are:
1. TRITON_ENABLE_STATS = OFF, TRITON_ENABLE_TRACING = OFF
1. TRITON_ENABLE_STATS = ON, TRITON_ENABLE_TRACING = OFF

Fixes #2137 

### Server without statistics extension:
```
root@285c0698ad37:/opt/tritonserver/qa/L0_grpc# /tmp/host/perf_analyzer -m simple -f test.csv
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 8308
    Throughput: 1661.6 infer/sec
    Avg latency: 600 usec (standard deviation 91 usec)
    p50 latency: 581 usec
    p90 latency: 681 usec
    p95 latency: 727 usec
    p99 latency: 944 usec
    Avg HTTP time: 597 usec (send/recv 66 usec + response wait 531 usec)
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 1661.6 infer/sec, latency 600 usec
```

### Server with statistics extension
```
root@285c0698ad37:/opt/tritonserver/qa/L0_grpc# /tmp/host/perf_analyzer -m simple -f test.csv
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 8234
    Throughput: 1646.8 infer/sec
    Avg latency: 606 usec (standard deviation 91 usec)
    p50 latency: 584 usec
    p90 latency: 692 usec
    p95 latency: 741 usec
    p99 latency: 946 usec
    Avg HTTP time: 600 usec (send/recv 67 usec + response wait 533 usec)
  Server: 
    Inference count: 9887
    Execution count: 9887
    Successful request count: 9887
    Avg request latency: 319 usec (overhead 35 usec + queue 21 usec + compute input 16 usec + compute infer 234 usec + compute output 13 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 1646.8 infer/sec, latency 606 usec
```

### CODE REVIEW

File: src/core/server.cc [hunk 1]
```diff
@@ -489,9 +489,10 @@ InferenceServer::InferAsync(std::unique_ptr<InferenceRequest>& request)
   }
 
 #ifdef TRITON_ENABLE_STATS
+  request->CaptureRequestStartNs();
   INFER_TRACE_ACTIVITY(
       request->Trace(), TRITONSERVER_TRACE_REQUEST_START,
-      request->CaptureRequestStartNs());
+      request->RequestStartNs());
 #endif  // TRITON_ENABLE_STATS
```
Comment (deadeyegoodwin) [inline src/core/server.cc:496]: EnsembleScheduler::Enqueue has the same problem of capturing a timestamp inside of a macro. Can you fix that as well (SequenceBatchScheduler::Enqueue has the correct code).

**Review by deadeyegoodwin — CHANGES_REQUESTED** [review]

**Review by deadeyegoodwin — APPROVED** [review]
